### PR TITLE
Added cover calculation to src/ModisL2GeoFile.cpp and side car creation.

### PR DESCRIPTION
**Pull request by captainkirk99**
Part of #38

### CODE REVIEW

**Comment by captainkirk99** [comment]
This is failing like this:

                 from ModisL2GeoFile.cpp:6:
```
/usr/include/c++/7/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = LatLonDegrees64; _Args = {}]’:
/usr/include/c++/7/bits/stl_uninitialized.h:527:18:   required from ‘static _ForwardIterator std::__uninitialized_default_n_1<_TrivialValueType>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator = LatLonDegrees64*; _Size = long unsigned int; bool _TrivialValueType = false]’
/usr/include/c++/7/bits/stl_uninitialized.h:583:20:   required from ‘_ForwardIterator std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator = LatLonDegrees64*; _Size = long unsigned int]’
/usr/include/c++/7/bits/stl_uninitialized.h:645:44:   required from ‘_ForwardIterator std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp>&) [with _ForwardIterator = LatLonDegrees64*; _Size = long unsigned int; _Tp = LatLonDegrees64]’
/usr/include/c++/7/bits/stl_vector.h:1352:36:   required from ‘void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = LatLonDegrees64; _Alloc = std::allocator<LatLonDegrees64>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/stl_vector.h:285:30:   required from ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&) [with _Tp = LatLonDegrees64; _Alloc = std::allocator<LatLonDegrees64>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<LatLonDegrees64>]’
ModisL2GeoFile.cpp:133:68:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: no matching function for call to ‘LatLonDegrees64::LatLonDegrees64()’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/stare/include/SkipListElement.h:17:0,
                 from /home/runner/stare/include/KeyPair.h:8,
                 from /home/runner/stare/include/HtmRangeMultiLevel.h:16,
                 from /home/runner/stare/include/HstmRange.h:9,
                 from /home/runner/stare/include/STARE.h:16,
                 from ../include/GeoFile.h:18,
                 from ../include/ModisL2GeoFile.h:15,
                 from ModisL2GeoFile.cpp:6:
/home/runner/stare/include/SpatialGeneral.h:227:2: note: candidate: LatLonDegrees64::LatLonDegrees64(float64, float64)
  LatLonDegrees64(float64 lat, float64 lon) : lat(lat), lon(lon) {}
  ^~~~~~~~~~~~~~~
/home/runner/stare/include/SpatialGeneral.h:227:2: note:   candidate expects 2 arguments, 0 provided
/home/runner/stare/include/SpatialGeneral.h:225:8: note: candidate: constexpr LatLonDegrees64::LatLonDegrees64(const LatLonDegrees64&)
 struct LatLonDegrees64 {
        ^~~~~~~~~~~~~~~
/home/runner/stare/include/SpatialGeneral.h:225:8: note:   candidate expects 1 argument, 0 provided

```

**Comment by captainkirk99** [comment]
@michaelleerilee does this require a new version of the STARE library? The testing is using 0.15.6.

**Comment by michaelleerilee** [comment]
Yes, my work with STAREmaster drove some small changes to STARE. I've pushed these to 0.16.1. I expect to get STARE 1.0 out this week.
 

    On Friday, September 11, 2020, 05:54:32 PM EDT, Captain James Tiberius Kirk <notifications@github.com> wrote:  
 
 


@michaelleerilee does this require a new version of the STARE library? The testing is using 0.15.6.

**Comment by captainkirk99** [comment]
ok I will update testing to use 0.15.6 and we will try this again. ;-)

**Comment by michaelleerilee** [comment]
Not sure 0.15.6 will do it. 0.16.1 has the patch to SpatialGeneral.h fixing that last build failure you mentioned.


Sent from Smallbiz Yahoo Mail for iPhone


On Saturday, September 12, 2020, 09:01, Captain James Tiberius Kirk <notifications@github.com> wrote:




ok I will update testing to use 0.15.6 and we will try this again. ;-)

**Comment by captainkirk99** [comment]
Sorry, I meant I will upgrade testing to use 0.16.1. ;-)

**Comment by captainkirk99** [comment]
OK, still getting segfaults when trying to generate covers for test files. I'm investigating...

**Comment by captainkirk99** [comment]
OK, this code passes on my machine but is failing on GitHub. ;-)
 I will continue to investigate...

**Comment by michaelleerilee** [comment]
I think we can merge this, updating the MOD05 functions.

**Pull request merged**
